name: deploy on push
on: [push]
jobs:
deploy-app:
runs-on: ubuntu-latest
step:
uses: actions/checkout@v2
uses: appleboy/scp-action@master
with:
host: ${{secrets.HOST}}
username: ${{secrets.SSH_USER_NAME}}
port: ${{secrets.SSH_PORT}}
key: ${{secrets.SSH_KEY}}
source: "./html/*"
target: "var/www/html"
strio_components: 1